env:
  JULIA_NUM_THREADS: auto

steps:
  - label: "Aggregate Docs"
    if: build.branch != "main"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - QuantumSavory/julia-xvfb#v1:
    command: |
      julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      julia -tauto --project=docs docs/make.jl --temp

  - label: "Deploy Docs"
    if: build.branch == "main"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - QuantumSavory/julia-xvfb#v1:
    secrets:
      DOCUMENTER_KEY: DOCUMENTER_KEY_multidoc
    command: |
      julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      git config user.name "QuantumSavory Buildkite"
      git config user.email "buildkite@quantumsavory.org"
      julia -tauto --project=docs docs/make.jl --temp deploy
